In [31]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nse-stocks-data/FINAL_FROM_DF.csv

In [32]:
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [33]:
data= pd.read_csv('/kaggle/input/nse-stocks-data/FINAL_FROM_DF.csv')
data.head()

,SYMBOL,SERIES,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TIMESTAMP,TOTALTRADES,ISIN
0,20MICRONS,EQ,37.80,37.80,36.15,36.85,37.40,37.05,27130,994657.90,2017-06-28,202,INE144J01027
1,3IINFOTECH,EQ,4.10,4.85,4.00,4.55,4.65,4.05,20157058,92148517.65,2017-06-28,7353,INE748C01020
2,3MINDIA,EQ,13425.15,13469.55,12920.00,13266.70,13300.00,13460.55,2290,30304923.35,2017-06-28,748,INE470A01017
3,63MOONS,EQ,61.00,61.90,60.35,61.00,61.10,60.65,27701,1689421.00,2017-06-28,437,INE111B01023
4,8KMILES,EQ,546.10,548.00,535.00,537.45,535.20,547.45,79722,43208620.05,2017-06-28,1866,INE650K01021

In [34]:
data.isna().any()

SYMBOL         False
SERIES          True
OPEN           False
HIGH           False
LOW            False
CLOSE          False
LAST           False
PREVCLOSE      False
TOTTRDQTY      False
TOTTRDVAL      False
TIMESTAMP      False
TOTALTRADES    False
ISIN           False
dtype: bool

In [35]:
data.isnull().sum()

SYMBOL            0
SERIES         2457
OPEN              0
HIGH              0
LOW               0
CLOSE             0
LAST              0
PREVCLOSE         0
TOTTRDQTY         0
TOTTRDVAL         0
TIMESTAMP         0
TOTALTRADES       0
ISIN              0
dtype: int64

In [36]:
data.describe()

,OPEN,HIGH,LOW,CLOSE,LAST,PREVCLOSE,TOTTRDQTY,TOTTRDVAL,TOTALTRADES
count,846404.000000,846404.000000,846404.000000,846404.000000,846404.000000,846404.000000,8.464040e+05,8.464040e+05,8.464040e+05
mean,561.258797,568.679340,553.861861,560.815168,560.184430,560.225320,6.983800e+05,1.334592e+08,5.013823e+03
std,2005.760598,2027.159199,1983.412783,2004.576315,2003.900793,2000.362761,4.055630e+06,6.296968e+08,1.490112e+04
min,0.050000,0.050000,0.050000,0.050000,0.000000,0.050000,1.000000e+00,5.000000e-02,1.000000e+00
25%,39.900000,40.850000,38.850000,39.750000,39.600000,39.700000,6.628000e+03,6.071941e+05,8.400000e+01
50%,139.200000,142.050000,136.150000,138.900000,138.450000,138.750000,4.429200e+04,5.321067e+06,6.000000e+02
75%,490.000000,499.550000,481.100000,489.550000,488.500000,489.150000,2.757322e+05,3.711093e+07,3.028000e+03
max,119990.000000,119990.000000,119990.000000,119990.000000,119990.000000,119990.000000,7.818365e+08,1.426400e+11,1.192900e+06

In [45]:
import sklearn 
from sklearn.model_selection import train_test_split
x=data[['OPEN','HIGH','LOW','LAST','PREVCLOSE','TOTTRDQTY','TOTALTRADES']]
y=data[['CLOSE']]
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)
print(np.shape(x_train), np.shape(y_train))

(634803, 7) (634803, 1)

In [38]:

from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion matrix, accuracy_score

In [51]:
instance=  LinearRegression()
instance.fit(x_train,y_train)
print(instance.coef_)
print(instance.intercept_)

[[-3.72261058e-01  5.72549882e-01  5.51463644e-01  2.41325116e-01
   6.71683375e-03  9.41284173e-09 -9.64000123e-07]]
[-0.22516001]

In [53]:
pred=instance.predict(x_test)
print(x_test)

           OPEN     HIGH      LOW     LAST  PREVCLOSE  TOTTRDQTY  TOTALTRADES
138389  1020.00  1020.00  1020.00  1020.00    1025.00        200            2
475580   329.55   331.80   319.65   324.50     328.35     122701         1885
766086   218.55   239.00   216.90   228.15     218.55     177369         3800
227989    10.49    10.49    10.49    10.49      10.40       1000            2
639233     0.90     0.95     0.90     0.90       0.90       1850            7
...         ...      ...      ...      ...        ...        ...          ...
314601    39.05    40.00    38.00    38.40      40.00     974630         2545
594395   189.55   192.50   185.50   186.00     188.70      44366          790
593329   271.75   278.00   271.00   277.00     270.10      57251          901
133802   487.00   492.90   472.50   477.00     487.10       8616          374
418865  2269.90  2269.90  2221.10  2250.00    2207.95        170           19

[211601 rows x 7 columns]

In [58]:
score=instance.score(x_test,y_test)
score

0.9999563587876749